### PR TITLE
Fix to previous PR

### PR DESCRIPTION
**Pull request by raj454raj**
Turns out that previous one worked for some of the pages. Check if this is not working for anything. I have tried many possibilities. Sorry!

### CODE REVIEW

**Comment by dhruvagarwal** [comment]
Nope. This doesn't work as well. Wait I'll have to do a fix for it.
If you're trying a few things please test on most of the pages.

**Comment by raj454raj** [comment]
For which URL is it not working?

**Comment by dhruvagarwal** [comment]
geeksforgeeks.org

**Comment by raj454raj** [comment]
screenshot from 2015-12-08 23 57 18
screenshot from 2015-12-08 23 56 47
screenshot from 2015-12-08 23 56 25

See in the console. I am successfully overriding the gfg site.
Give me a screenshot of the console. Check if that css file is actually loaded or not.

**Comment by raj454raj** [comment]
You will obviously need to disable the actual one and load only this extension from filesystem.

**Comment by dhruvagarwal** [comment]
Obviously ! but 
screenshot from 2015-12-09 00 01 55

**Comment by raj454raj** [comment]
Give me the screenshot of "inspect element" of that input checkbox

**Comment by dhruvagarwal** [comment]
@raj454raj You're right ! my chrome was caching .. though i was hard refreshing but still couldnt get it right. 
Tried it in incognito and that worked. 

Thanks !

**Comment by raj454raj** [comment]
I think the previous PR was also correct ! :smile: :D

**Pull request merged**
